level1 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W  P                                   W",
    "W         WWWWWW   WW         WWWWWW   W",
    "W   WWWW       W   WW   WWWW       W   W",
    "W   W        WWWW  WW   W        WWWW  W",
    "W WWW  WWWW        WW WWW  WWWW        W",
    "W   W     W W      WW   W     W W      W",
    "W   W     W   WWW WWW   W     W   WWW WW",
    "W   WWW WWW   W W  WW   WWW WWW   W W  W",
    "W     W   W   W W  WW     W   W   W W  W",
    "WWW   W   WWWWW W  WWWW   W   WWWWW W  W",
    "W W      WW        WW W      WW        W",
    "W W   WWWW   WWW   WW W   WWWW   WWW   W",
    "W     W        W   WW     W        W E W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
];


level2 =[
    "WWWWWWWWWWWWWWWWWWWW",
    "WP                 W",
    "W       WWWWWWWW   W",
    "W   WWWW       W   W",
    "W   W  W     WWWW  W",
    "W WWW  W WW        W",
    "W   W     W W      W",
    "W   W     W   WWW WW",
    "W   WWW WWW   W W  W",
    "W     W   W   W W  W",
    "WWW   W E WW WW W  W",
    "W W   W  WW        W",
    "W W   W  W WWWWW   W",
    "W     W            W",
    "WWWWWWWWWWWWWWWWWWWW",
];
level3 =[
    "WWWWWWWWWWWWWWWWWWWW",
    "W                  W",
    "W   WWWWWWWWWWWW   W",
    "W   W          W   W",
    "W      WWWWWWWWW   W",
    "W   W      W       W",
    "W   W  W   W   W   W",
    "W   WWWWW WWWW W   W",
    "W   W        W W   W",
    "W   WWWWWWWW W W   W",
    "W   W    W   W W   W",
    "W   W W WWWWWW W   W",
    "W P WEW        W   W",
    "W   WWWWWWWWWWWW   W",
    "WWWWWWWWWWWWWWWWWWWW",
];